# This file was generated by GoReleaser. DO NOT EDIT.
cask "brink" do
  version "0.4.2"

  on_macos do
    on_intel do
      sha256 "0f8607076e746f363ccc1a87f4bf52c7105ef4463b52bf4145b29f6a883fc602"
      url "https://github.com/getbrink/brink/releases/download/v#{version}/brink_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "52250b151b4d2c520fd8c0b2d91366d8bae7dd03cec32abcfd5a775fefb43500"
      url "https://github.com/getbrink/brink/releases/download/v#{version}/brink_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "592963bb58887f408af47ec60992237a87a88eb81d523dc9123c9e784cde2a49"
      url "https://github.com/getbrink/brink/releases/download/v#{version}/brink_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "deb4219308801fcccc56211eb3fe7bc1adc3012b52601dc5436208b37dd7cd3e"
      url "https://github.com/getbrink/brink/releases/download/v#{version}/brink_#{version}_linux_arm64.tar.gz"
    end
  end

  name "brink"
  desc "Reliability control loop operator CLI for AI agents."
  homepage "https://docs.getbrink.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "brink"
  manpage "man/brink.1"
  bash_completion "completions/brink.bash"
  fish_completion "completions/brink.fish"
  zsh_completion "completions/brink.zsh"

  # No zap stanza required

end
