# This file was generated by GoReleaser. DO NOT EDIT.
cask "brink" do
  require "download_strategy"
  class GitHubPrivateRepositoryReleaseDownloadStrategy < CurlDownloadStrategy
    def initialize(url, name, version, **meta)
      @url = url
      parse_url_pattern
      @github_token = ENV["HOMEBREW_GITHUB_API_TOKEN"]
      if @github_token
        validate_github_access
        meta[:headers] ||= []
        meta[:headers] << "Accept: application/octet-stream"
        meta[:headers] << "Authorization: Bearer #{@github_token}"
        ghurl = "https://api.github.com/repos/#{@owner}/#{@repo}/releases/assets/#{asset_id}"
        super(ghurl, name, version, **meta)
      else
        super(@url, name, version, **meta)
      end
    end

    def parse_url_pattern
      url_pattern = %r{https://github.com/([^/]+)/([^/]+)/releases/download/([^/]+)/(\S+)}
      raise CurlDownloadStrategyError, "Invalid url pattern" unless @url =~ url_pattern
      _, @owner, @repo, @tag, @filename = *@url.match(url_pattern)
    end

    def download_url
      return @url unless @github_token
      "https://#{@github_token}@api.github.com/repos/#{@owner}/#{@repo}/releases/assets/#{asset_id}"
    end

    private

    def validate_github_access
      GitHub.repository(@owner, @repo)
    end

    def asset_id
      @asset_id ||= GitHub.get_release(@owner, @repo, @tag)["assets"]
                        .find { |a| a["name"] == @filename }
                        .fetch("id") { raise CurlDownloadStrategyError, "Asset not found" }
    end
  end

  version "0.4.5"

  on_macos do
    on_intel do
      sha256 "06d19150a63691268b8de11fe048249f27d2f2c3c46d74e2e205abd2fff1e127"
      url "https://github.com/getbrink/brink/releases/download/v#{version}/brink_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/getbrink/brink/",
        using: GitHubPrivateRepositoryReleaseDownloadStrategy
    end
    on_arm do
      sha256 "58610cc2aca11b862eb4dadea8dca60842f9b52fba129009deeb500a63df5649"
      url "https://github.com/getbrink/brink/releases/download/v#{version}/brink_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/getbrink/brink/",
        using: GitHubPrivateRepositoryReleaseDownloadStrategy
    end
  end

  on_linux do
    on_intel do
      sha256 "38fac48151ca2558007b5e0275b3faa4089d5263e94cf1f33bbd86b93e528e34"
      url "https://github.com/getbrink/brink/releases/download/v#{version}/brink_#{version}_linux_amd64.tar.gz",
        verified: "github.com/getbrink/brink/",
        using: GitHubPrivateRepositoryReleaseDownloadStrategy
    end
    on_arm do
      sha256 "7619e9bca54c9805de7ac2da73dc1f1829373188fa832b808369f28861eb98f0"
      url "https://github.com/getbrink/brink/releases/download/v#{version}/brink_#{version}_linux_arm64.tar.gz",
        verified: "github.com/getbrink/brink/",
        using: GitHubPrivateRepositoryReleaseDownloadStrategy
    end
  end

  name "brink"
  desc "Reliability control loop operator CLI for AI agents."
  homepage "https://docs.getbrink.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "brink"
  manpage "man/brink.1"
  bash_completion "completions/brink.bash"
  fish_completion "completions/brink.fish"
  zsh_completion "completions/brink.zsh"

  # No zap stanza required

end
