# This file was generated by GoReleaser. DO NOT EDIT.
cask "brink" do
  require "download_strategy"
  class GitHubPrivateRepositoryReleaseDownloadStrategy < CurlDownloadStrategy
    def initialize(url, name, version, **meta)
      @url = url
      parse_url_pattern
      @github_token = ENV["HOMEBREW_GITHUB_API_TOKEN"]
      if @github_token
        validate_github_access
        meta[:headers] ||= []
        meta[:headers] << "Accept: application/octet-stream"
        meta[:headers] << "Authorization: Bearer #{@github_token}"
        ghurl = "https://api.github.com/repos/#{@owner}/#{@repo}/releases/assets/#{asset_id}"
        super(ghurl, name, version, **meta)
      else
        super(@url, name, version, **meta)
      end
    end

    def parse_url_pattern
      url_pattern = %r{https://github.com/([^/]+)/([^/]+)/releases/download/([^/]+)/(\S+)}
      raise CurlDownloadStrategyError, "Invalid url pattern" unless @url =~ url_pattern
      _, @owner, @repo, @tag, @filename = *@url.match(url_pattern)
    end

    def download_url
      return @url unless @github_token
      "https://#{@github_token}@api.github.com/repos/#{@owner}/#{@repo}/releases/assets/#{asset_id}"
    end

    private

    def validate_github_access
      GitHub.repository(@owner, @repo)
    end

    def asset_id
      @asset_id ||= GitHub.get_release(@owner, @repo, @tag)["assets"]
                        .find { |a| a["name"] == @filename }
                        .fetch("id") { raise CurlDownloadStrategyError, "Asset not found" }
    end
  end

  version "0.4.3"

  on_macos do
    on_intel do
      sha256 "8597ddab34b92f58946e10853baa8e5ea787dd9f4d6b11dfee0761e7bfda7bca"
      url "https://github.com/getbrink/brink/releases/download/v#{version}/brink_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/getbrink/brink/",
        using: GitHubPrivateRepositoryReleaseDownloadStrategy
    end
    on_arm do
      sha256 "09ab0e5267839c6501d84e7d551955abaa7502ec3059e2cb2916044feecc809a"
      url "https://github.com/getbrink/brink/releases/download/v#{version}/brink_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/getbrink/brink/",
        using: GitHubPrivateRepositoryReleaseDownloadStrategy
    end
  end

  on_linux do
    on_intel do
      sha256 "ea89099f339bf6ea574ae727003e4e4e4c9e0f9d0346ec035caaf85b9f3fb8f7"
      url "https://github.com/getbrink/brink/releases/download/v#{version}/brink_#{version}_linux_amd64.tar.gz",
        verified: "github.com/getbrink/brink/",
        using: GitHubPrivateRepositoryReleaseDownloadStrategy
    end
    on_arm do
      sha256 "19b600b7cb5fe5e0042895bbddb8359f39b716f7aacf0779419bbcdd81193e6e"
      url "https://github.com/getbrink/brink/releases/download/v#{version}/brink_#{version}_linux_arm64.tar.gz",
        verified: "github.com/getbrink/brink/",
        using: GitHubPrivateRepositoryReleaseDownloadStrategy
    end
  end

  name "brink"
  desc "Reliability control loop operator CLI for AI agents."
  homepage "https://docs.getbrink.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "brink"
  manpage "man/brink.1"
  bash_completion "completions/brink.bash"
  fish_completion "completions/brink.fish"
  zsh_completion "completions/brink.zsh"

  # No zap stanza required

end
