# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../lib/custom_download_strategy"
class Brink < Formula
  desc "Reliability control loop operator CLI for AI agents."
  homepage "https://docs.getbrink.dev"
  version "0.5.5"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://dl.getbrink.dev/brew/v0.5.5/brink_0.5.5_darwin_amd64.tar.gz", using: BrinkBrokerDownloadStrategy
      sha256 "b084b307525b82efe9e633bae84cb2b788750cc784a4024fbf75c89ac2293b9d"

      define_method(:install) do
        bin.install "brink"
        man1.install "man/brink.1"
        bash_completion.install "completions/brink.bash" => "brink"
        zsh_completion.install "completions/brink.zsh" => "_brink"
        fish_completion.install "completions/brink.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://dl.getbrink.dev/brew/v0.5.5/brink_0.5.5_darwin_arm64.tar.gz", using: BrinkBrokerDownloadStrategy
      sha256 "ebc132388ffeee09cadc5d28d26a80784468a261db858c9bda8e96d891c00986"

      define_method(:install) do
        bin.install "brink"
        man1.install "man/brink.1"
        bash_completion.install "completions/brink.bash" => "brink"
        zsh_completion.install "completions/brink.zsh" => "_brink"
        fish_completion.install "completions/brink.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://dl.getbrink.dev/brew/v0.5.5/brink_0.5.5_linux_amd64.tar.gz", using: BrinkBrokerDownloadStrategy
      sha256 "2d4d68e8efd6e1561525d446ec623e4be801522ef76373c31a0e65930b74820f"
      define_method(:install) do
        bin.install "brink"
        man1.install "man/brink.1"
        bash_completion.install "completions/brink.bash" => "brink"
        zsh_completion.install "completions/brink.zsh" => "_brink"
        fish_completion.install "completions/brink.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://dl.getbrink.dev/brew/v0.5.5/brink_0.5.5_linux_arm64.tar.gz", using: BrinkBrokerDownloadStrategy
      sha256 "771a7649d0b88a4a9888dbbc6402b12fbb99225443e92f92826a347a40fe3bab"
      define_method(:install) do
        bin.install "brink"
        man1.install "man/brink.1"
        bash_completion.install "completions/brink.bash" => "brink"
        zsh_completion.install "completions/brink.zsh" => "_brink"
        fish_completion.install "completions/brink.fish"
      end
    end
  end

  test do
    system "#{bin}/brink", "version", "--client"
  end
end
