# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../lib/custom_download_strategy"
class Brink < Formula
  desc "Reliability control loop operator CLI for AI agents."
  homepage "https://docs.getbrink.dev"
  version "0.5.8"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://dl.getbrink.dev/brew/v0.5.8/brink_0.5.8_darwin_amd64.tar.gz", using: BrinkBrokerDownloadStrategy
      sha256 "044ce665abef0484afc3edfdd6de5131faa501802f4cd232dd518cf390ad551e"

      define_method(:install) do
        bin.install "brink"
        man1.install "man/brink.1"
        bash_completion.install "completions/brink.bash" => "brink"
        zsh_completion.install "completions/brink.zsh" => "_brink"
        fish_completion.install "completions/brink.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://dl.getbrink.dev/brew/v0.5.8/brink_0.5.8_darwin_arm64.tar.gz", using: BrinkBrokerDownloadStrategy
      sha256 "d157476186512413b1f24c392c0da1d7a2ece21a5bd7d1e11df9216780bdb910"

      define_method(:install) do
        bin.install "brink"
        man1.install "man/brink.1"
        bash_completion.install "completions/brink.bash" => "brink"
        zsh_completion.install "completions/brink.zsh" => "_brink"
        fish_completion.install "completions/brink.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://dl.getbrink.dev/brew/v0.5.8/brink_0.5.8_linux_amd64.tar.gz", using: BrinkBrokerDownloadStrategy
      sha256 "88f89e5d7121861520fb12e73eab0f2d5fd57e501e9121dc86ef413a1f3069e4"
      define_method(:install) do
        bin.install "brink"
        man1.install "man/brink.1"
        bash_completion.install "completions/brink.bash" => "brink"
        zsh_completion.install "completions/brink.zsh" => "_brink"
        fish_completion.install "completions/brink.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://dl.getbrink.dev/brew/v0.5.8/brink_0.5.8_linux_arm64.tar.gz", using: BrinkBrokerDownloadStrategy
      sha256 "486b1f744593018d96c68cdfaa858d235d1ca6f10e80fdb490da20f3a773948d"
      define_method(:install) do
        bin.install "brink"
        man1.install "man/brink.1"
        bash_completion.install "completions/brink.bash" => "brink"
        zsh_completion.install "completions/brink.zsh" => "_brink"
        fish_completion.install "completions/brink.fish"
      end
    end
  end

  test do
    system "#{bin}/brink", "version", "--client"
  end
end
